
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.Action NewAction;
	
	private global::Gtk.Action NewTournamentAction;
	
	private global::Gtk.Action NewPlayerAction;
	
	private global::Gtk.Action LoadAction;
	
	private global::Gtk.Action SaveTournamentAction;
	
	private global::Gtk.Action LoadTournamentAction;
	
	private global::Gtk.Action LoadAutosaveAction;
	
	private global::Gtk.Action LoadAutosavefileAction;
	
	private global::Gtk.Action ShowAutosaveAction;
	
	private global::Gtk.Action LoadAutosavefileAction1;
	
	private global::Gtk.Action ImportExportAction;
	
	private global::Gtk.Action ImportFromT3Action;
	
	private global::Gtk.Action ExportToT3Action;
	
	private global::Gtk.Action ExportToBBCodeAction;
	
	private global::Gtk.Action PrintAction;
	
	private global::Gtk.Action PrintTableAction;
	
	private global::Gtk.Action PrintPairingsAction;
	
	private global::Gtk.Action PrintPairingsWithResultsAction;
	
	private global::Gtk.Action QuitAction;
	
	private global::Gtk.Action PrintScoresheetAction;
	
	private global::Gtk.Action TournamentAction;
	
	private global::Gtk.Action ChangePairingsAction;
	
	private global::Gtk.Action ResetLastResultsAction;
	
	private global::Gtk.Action TournamentSettingsAction;
	
	private global::Gtk.Action ChangePlayerAction;
	
	private global::Gtk.Action RemovePlayerAction;
	
	private global::Gtk.Action ToolsAction;
	
	private global::Gtk.Action TimerAction;
	
	private global::Gtk.Action RandomizerAction;
	
	private global::Gtk.Action ShowTablePairingsAction;
	
	private global::Gtk.Action LanguageAction;
	
	private global::Gtk.Action LoadLanguagesAction;
	
	private global::Gtk.Action DefaultLanguageEnglishAction;
	
	private global::Gtk.Action HelpAction;
	
	private global::Gtk.Action AboutTXMAction;
	
	private global::Gtk.Action ShowsTimeForTOAction;
	
	private global::Gtk.Action StartTimerAction;
	
	private global::Gtk.Action PauseTimerAction;
	
	private global::Gtk.Action ResetTimerAction;
	
	private global::Gtk.Action SetTimeAction;
	
	private global::Gtk.Action T30MinutesAction;
	
	private global::Gtk.Action T45MinutesAction;
	
	private global::Gtk.Action T60MinutesAction;
	
	private global::Gtk.Action T75MinutesAction;
	
	private global::Gtk.Action T90MinutesAction;
	
	private global::Gtk.Action VariableAction;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.MenuBar menubar1;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Button button29;
	
	private global::Gtk.Button button30;
	
	private global::Gtk.Button button31;
	
	private global::Gtk.Button button32;
	
	private global::Gtk.HPaned hpaned1;
	
	private global::Gtk.VPaned vpaned1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.NewAction = new global::Gtk.Action ("NewAction", global::Mono.Unix.Catalog.GetString ("New"), null, null);
		this.NewAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("New");
		w1.Add (this.NewAction, null);
		this.NewTournamentAction = new global::Gtk.Action ("NewTournamentAction", global::Mono.Unix.Catalog.GetString ("New Tournament"), null, null);
		this.NewTournamentAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("New Tournament");
		w1.Add (this.NewTournamentAction, null);
		this.NewPlayerAction = new global::Gtk.Action ("NewPlayerAction", global::Mono.Unix.Catalog.GetString ("New Player"), null, null);
		this.NewPlayerAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("New Player");
		w1.Add (this.NewPlayerAction, null);
		this.LoadAction = new global::Gtk.Action ("LoadAction", global::Mono.Unix.Catalog.GetString ("Load"), null, null);
		this.LoadAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Load");
		w1.Add (this.LoadAction, null);
		this.SaveTournamentAction = new global::Gtk.Action ("SaveTournamentAction", global::Mono.Unix.Catalog.GetString ("Save Tournament"), null, null);
		this.SaveTournamentAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save Tournament");
		w1.Add (this.SaveTournamentAction, null);
		this.LoadTournamentAction = new global::Gtk.Action ("LoadTournamentAction", global::Mono.Unix.Catalog.GetString ("Load Tournament"), null, null);
		this.LoadTournamentAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Load Tournament");
		w1.Add (this.LoadTournamentAction, null);
		this.LoadAutosaveAction = new global::Gtk.Action ("LoadAutosaveAction", global::Mono.Unix.Catalog.GetString ("Load Autosave"), null, null);
		this.LoadAutosaveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Load Autosave");
		w1.Add (this.LoadAutosaveAction, null);
		this.LoadAutosavefileAction = new global::Gtk.Action ("LoadAutosavefileAction", global::Mono.Unix.Catalog.GetString ("Load Autosavefile"), null, null);
		this.LoadAutosavefileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Load Autosavefile");
		w1.Add (this.LoadAutosavefileAction, null);
		this.ShowAutosaveAction = new global::Gtk.Action ("ShowAutosaveAction", global::Mono.Unix.Catalog.GetString ("Show Autosave"), null, null);
		this.ShowAutosaveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Show Autosave");
		w1.Add (this.ShowAutosaveAction, null);
		this.LoadAutosavefileAction1 = new global::Gtk.Action ("LoadAutosavefileAction1", global::Mono.Unix.Catalog.GetString ("Load Autosavefile"), null, null);
		this.LoadAutosavefileAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Load Autosavefile");
		w1.Add (this.LoadAutosavefileAction1, null);
		this.ImportExportAction = new global::Gtk.Action ("ImportExportAction", global::Mono.Unix.Catalog.GetString ("Import / Export"), null, null);
		this.ImportExportAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Import / Export");
		w1.Add (this.ImportExportAction, null);
		this.ImportFromT3Action = new global::Gtk.Action ("ImportFromT3Action", global::Mono.Unix.Catalog.GetString ("Import from T3"), null, null);
		this.ImportFromT3Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("Import from T3");
		w1.Add (this.ImportFromT3Action, null);
		this.ExportToT3Action = new global::Gtk.Action ("ExportToT3Action", global::Mono.Unix.Catalog.GetString ("Export to T3"), null, null);
		this.ExportToT3Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("Export to T3");
		w1.Add (this.ExportToT3Action, null);
		this.ExportToBBCodeAction = new global::Gtk.Action ("ExportToBBCodeAction", global::Mono.Unix.Catalog.GetString ("Export to BBCode"), null, null);
		this.ExportToBBCodeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Export to BBCode");
		w1.Add (this.ExportToBBCodeAction, null);
		this.PrintAction = new global::Gtk.Action ("PrintAction", global::Mono.Unix.Catalog.GetString ("Print"), null, null);
		this.PrintAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Print");
		w1.Add (this.PrintAction, null);
		this.PrintTableAction = new global::Gtk.Action ("PrintTableAction", global::Mono.Unix.Catalog.GetString ("Print Table"), null, null);
		this.PrintTableAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Print Table");
		w1.Add (this.PrintTableAction, null);
		this.PrintPairingsAction = new global::Gtk.Action ("PrintPairingsAction", global::Mono.Unix.Catalog.GetString ("Print Pairings"), null, null);
		this.PrintPairingsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Print Pairings");
		w1.Add (this.PrintPairingsAction, null);
		this.PrintPairingsWithResultsAction = new global::Gtk.Action ("PrintPairingsWithResultsAction", global::Mono.Unix.Catalog.GetString ("Print Pairings with results"), null, null);
		this.PrintPairingsWithResultsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Print Pairings with results");
		w1.Add (this.PrintPairingsWithResultsAction, null);
		this.QuitAction = new global::Gtk.Action ("QuitAction", global::Mono.Unix.Catalog.GetString ("Quit"), null, null);
		this.QuitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
		w1.Add (this.QuitAction, null);
		this.PrintScoresheetAction = new global::Gtk.Action ("PrintScoresheetAction", global::Mono.Unix.Catalog.GetString ("Print Scoresheet"), null, null);
		this.PrintScoresheetAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Print Scoresheet");
		w1.Add (this.PrintScoresheetAction, null);
		this.TournamentAction = new global::Gtk.Action ("TournamentAction", global::Mono.Unix.Catalog.GetString ("Tournament"), null, null);
		this.TournamentAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Tournament");
		w1.Add (this.TournamentAction, null);
		this.ChangePairingsAction = new global::Gtk.Action ("ChangePairingsAction", global::Mono.Unix.Catalog.GetString ("Change Pairings"), null, null);
		this.ChangePairingsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Change Pairings");
		w1.Add (this.ChangePairingsAction, null);
		this.ResetLastResultsAction = new global::Gtk.Action ("ResetLastResultsAction", global::Mono.Unix.Catalog.GetString ("Reset Last Results"), null, null);
		this.ResetLastResultsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Reset Last Results");
		w1.Add (this.ResetLastResultsAction, null);
		this.TournamentSettingsAction = new global::Gtk.Action ("TournamentSettingsAction", global::Mono.Unix.Catalog.GetString ("Tournament Settings"), null, null);
		this.TournamentSettingsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Tournament Settings");
		w1.Add (this.TournamentSettingsAction, null);
		this.ChangePlayerAction = new global::Gtk.Action ("ChangePlayerAction", global::Mono.Unix.Catalog.GetString ("Change Player"), null, null);
		this.ChangePlayerAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Change Player");
		w1.Add (this.ChangePlayerAction, null);
		this.RemovePlayerAction = new global::Gtk.Action ("RemovePlayerAction", global::Mono.Unix.Catalog.GetString ("Remove Player"), null, null);
		this.RemovePlayerAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Remove Player");
		w1.Add (this.RemovePlayerAction, null);
		this.ToolsAction = new global::Gtk.Action ("ToolsAction", global::Mono.Unix.Catalog.GetString ("Tools"), null, null);
		this.ToolsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Tools");
		w1.Add (this.ToolsAction, null);
		this.TimerAction = new global::Gtk.Action ("TimerAction", global::Mono.Unix.Catalog.GetString ("Timer"), null, null);
		this.TimerAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Timer");
		w1.Add (this.TimerAction, null);
		this.RandomizerAction = new global::Gtk.Action ("RandomizerAction", global::Mono.Unix.Catalog.GetString ("Randomizer"), null, null);
		this.RandomizerAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Randomizer");
		w1.Add (this.RandomizerAction, null);
		this.ShowTablePairingsAction = new global::Gtk.Action ("ShowTablePairingsAction", global::Mono.Unix.Catalog.GetString ("Show Table & Pairings"), null, null);
		this.ShowTablePairingsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Show Table & Pairings");
		w1.Add (this.ShowTablePairingsAction, null);
		this.LanguageAction = new global::Gtk.Action ("LanguageAction", global::Mono.Unix.Catalog.GetString ("Language"), null, null);
		this.LanguageAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Language");
		w1.Add (this.LanguageAction, null);
		this.LoadLanguagesAction = new global::Gtk.Action ("LoadLanguagesAction", global::Mono.Unix.Catalog.GetString ("Load Languages"), null, null);
		this.LoadLanguagesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Load Languages");
		w1.Add (this.LoadLanguagesAction, null);
		this.DefaultLanguageEnglishAction = new global::Gtk.Action ("DefaultLanguageEnglishAction", global::Mono.Unix.Catalog.GetString ("Default Language (english)"), null, null);
		this.DefaultLanguageEnglishAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Default Language (english)");
		w1.Add (this.DefaultLanguageEnglishAction, null);
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.HelpAction, null);
		this.AboutTXMAction = new global::Gtk.Action ("AboutTXMAction", global::Mono.Unix.Catalog.GetString ("About TXM"), null, null);
		this.AboutTXMAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About TXM");
		w1.Add (this.AboutTXMAction, null);
		this.ShowsTimeForTOAction = new global::Gtk.Action ("ShowsTimeForTOAction", global::Mono.Unix.Catalog.GetString ("Shows Time for TO"), null, null);
		this.ShowsTimeForTOAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Shows Time for TO");
		w1.Add (this.ShowsTimeForTOAction, null);
		this.StartTimerAction = new global::Gtk.Action ("StartTimerAction", global::Mono.Unix.Catalog.GetString ("Start Timer"), null, null);
		this.StartTimerAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Start Timer");
		w1.Add (this.StartTimerAction, null);
		this.PauseTimerAction = new global::Gtk.Action ("PauseTimerAction", global::Mono.Unix.Catalog.GetString ("Pause Timer"), null, null);
		this.PauseTimerAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Pause Timer");
		w1.Add (this.PauseTimerAction, null);
		this.ResetTimerAction = new global::Gtk.Action ("ResetTimerAction", global::Mono.Unix.Catalog.GetString ("Reset Timer"), null, null);
		this.ResetTimerAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Reset Timer");
		w1.Add (this.ResetTimerAction, null);
		this.SetTimeAction = new global::Gtk.Action ("SetTimeAction", global::Mono.Unix.Catalog.GetString ("Set Time"), null, null);
		this.SetTimeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Set Time");
		w1.Add (this.SetTimeAction, null);
		this.T30MinutesAction = new global::Gtk.Action ("T30MinutesAction", global::Mono.Unix.Catalog.GetString ("30 Minutes"), null, null);
		this.T30MinutesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("30 Minutes");
		w1.Add (this.T30MinutesAction, null);
		this.T45MinutesAction = new global::Gtk.Action ("T45MinutesAction", global::Mono.Unix.Catalog.GetString ("45 Minutes"), null, null);
		this.T45MinutesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("45 Minutes");
		w1.Add (this.T45MinutesAction, null);
		this.T60MinutesAction = new global::Gtk.Action ("T60MinutesAction", global::Mono.Unix.Catalog.GetString ("60 Minutes"), null, null);
		this.T60MinutesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("60 Minutes");
		w1.Add (this.T60MinutesAction, null);
		this.T75MinutesAction = new global::Gtk.Action ("T75MinutesAction", global::Mono.Unix.Catalog.GetString ("75 Minutes"), null, null);
		this.T75MinutesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("75 Minutes");
		w1.Add (this.T75MinutesAction, null);
		this.T90MinutesAction = new global::Gtk.Action ("T90MinutesAction", global::Mono.Unix.Catalog.GetString ("90 Minutes"), null, null);
		this.T90MinutesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("90 Minutes");
		w1.Add (this.T90MinutesAction, null);
		this.VariableAction = new global::Gtk.Action ("VariableAction", global::Mono.Unix.Catalog.GetString ("Variable"), null, null);
		this.VariableAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Variable");
		w1.Add (this.VariableAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name=\'menubar1\'><menu name=\'FileAction\' action=\'FileAction\'><menu na" +
		"me=\'NewAction\' action=\'NewAction\'><menuitem name=\'NewTournamentAction\' action=\'N" +
		"ewTournamentAction\'/><menuitem name=\'NewPlayerAction\' action=\'NewPlayerAction\'/>" +
		"</menu><menu name=\'LoadAction\' action=\'LoadAction\'><menuitem name=\'LoadTournamen" +
		"tAction\' action=\'LoadTournamentAction\'/><menuitem name=\'LoadAutosavefileAction1\'" +
		" action=\'LoadAutosavefileAction1\'/></menu><menuitem name=\'SaveTournamentAction\' " +
		"action=\'SaveTournamentAction\'/><menu name=\'ImportExportAction\' action=\'ImportExp" +
		"ortAction\'><menuitem name=\'ImportFromT3Action\' action=\'ImportFromT3Action\'/><men" +
		"uitem name=\'ExportToT3Action\' action=\'ExportToT3Action\'/><menuitem name=\'ExportT" +
		"oBBCodeAction\' action=\'ExportToBBCodeAction\'/></menu><menu name=\'PrintAction\' ac" +
		"tion=\'PrintAction\'><menuitem name=\'PrintTableAction\' action=\'PrintTableAction\'/>" +
		"<menuitem name=\'PrintPairingsAction\' action=\'PrintPairingsAction\'/><menuitem nam" +
		"e=\'PrintPairingsWithResultsAction\' action=\'PrintPairingsWithResultsAction\'/><men" +
		"uitem name=\'PrintScoresheetAction\' action=\'PrintScoresheetAction\'/></menu><menui" +
		"tem name=\'QuitAction\' action=\'QuitAction\'/></menu><menu name=\'TournamentAction\' " +
		"action=\'TournamentAction\'><menuitem name=\'ChangePairingsAction\' action=\'ChangePa" +
		"iringsAction\'/><menuitem name=\'ResetLastResultsAction\' action=\'ResetLastResultsA" +
		"ction\'/><menuitem name=\'TournamentSettingsAction\' action=\'TournamentSettingsActi" +
		"on\'/><menuitem name=\'ChangePlayerAction\' action=\'ChangePlayerAction\'/><menuitem " +
		"name=\'RemovePlayerAction\' action=\'RemovePlayerAction\'/><menuitem name=\'ShowTable" +
		"PairingsAction\' action=\'ShowTablePairingsAction\'/></menu><menu name=\'ToolsAction" +
		"\' action=\'ToolsAction\'><menuitem name=\'TimerAction\' action=\'TimerAction\'/><menui" +
		"tem name=\'RandomizerAction\' action=\'RandomizerAction\'/><menu name=\'LanguageActio" +
		"n\' action=\'LanguageAction\'><menuitem name=\'LoadLanguagesAction\' action=\'LoadLang" +
		"uagesAction\'/><menuitem name=\'DefaultLanguageEnglishAction\' action=\'DefaultLangu" +
		"ageEnglishAction\'/></menu></menu><menu name=\'HelpAction\' action=\'HelpAction\'><me" +
		"nuitem name=\'AboutTXMAction\' action=\'AboutTXMAction\'/></menu><menu name=\'ShowsTi" +
		"meForTOAction\' action=\'ShowsTimeForTOAction\'><menuitem name=\'StartTimerAction\' a" +
		"ction=\'StartTimerAction\'/><menuitem name=\'PauseTimerAction\' action=\'PauseTimerAc" +
		"tion\'/><menuitem name=\'ResetTimerAction\' action=\'ResetTimerAction\'/><menu name=\'" +
		"SetTimeAction\' action=\'SetTimeAction\'><menuitem name=\'T30MinutesAction\' action=\'" +
		"T30MinutesAction\'/><menuitem name=\'T45MinutesAction\' action=\'T45MinutesAction\'/>" +
		"<menuitem name=\'T60MinutesAction\' action=\'T60MinutesAction\'/><menuitem name=\'T75" +
		"MinutesAction\' action=\'T75MinutesAction\'/><menuitem name=\'T90MinutesAction\' acti" +
		"on=\'T90MinutesAction\'/><menuitem name=\'VariableAction\' action=\'VariableAction\'/>" +
		"</menu></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		// Container child hbox1.Gtk.Box+BoxChild
		this.button29 = new global::Gtk.Button ();
		this.button29.CanFocus = true;
		this.button29.Name = "button29";
		this.button29.UseUnderline = true;
		this.button29.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbox1.Add (this.button29);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button29]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button30 = new global::Gtk.Button ();
		this.button30.CanFocus = true;
		this.button30.Name = "button30";
		this.button30.UseUnderline = true;
		this.button30.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbox1.Add (this.button30);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button30]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button31 = new global::Gtk.Button ();
		this.button31.CanFocus = true;
		this.button31.Name = "button31";
		this.button31.UseUnderline = true;
		this.button31.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbox1.Add (this.button31);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button31]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button32 = new global::Gtk.Button ();
		this.button32.CanFocus = true;
		this.button32.Name = "button32";
		this.button32.UseUnderline = true;
		this.button32.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbox1.Add (this.button32);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button32]));
		w6.Position = 3;
		w6.Expand = false;
		w6.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hpaned1 = new global::Gtk.HPaned ();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 122;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vpaned1 = new global::Gtk.VPaned ();
		this.vpaned1.CanFocus = true;
		this.vpaned1.Name = "vpaned1";
		this.vpaned1.Position = 40;
		this.hpaned1.Add (this.vpaned1);
		this.vbox1.Add (this.hpaned1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hpaned1]));
		w9.Position = 2;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 518;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
