
// This file has been generated by the GUI designer. Do not modify.
namespace TXM
{
	public partial class PlayerDialog
	{
		private global::Gtk.Notebook notebook1;
		
		private global::Gtk.Table table1;
		
		private global::Gtk.CheckButton checkbuttonPresent;
		
		private global::Gtk.ComboBox comboboxFaction;
		
		private global::Gtk.Entry entryForeName;
		
		private global::Gtk.Entry entryLastName;
		
		private global::Gtk.Entry entryNickName;
		
		private global::Gtk.Entry entryTeam;
		
		private global::Gtk.Label labelFaction;
		
		private global::Gtk.Label labelForeName;
		
		private global::Gtk.Label labelInfoName;
		
		private global::Gtk.Label labelLastName;
		
		private global::Gtk.Label labelNickname;
		
		private global::Gtk.Label labelTeam;
		
		private global::Gtk.Label labelTabBasic;
		
		private global::Gtk.Table table3;
		
		private global::Gtk.CheckButton checkbuttonDisqualified;
		
		private global::Gtk.CheckButton checkbuttonPaid;
		
		private global::Gtk.CheckButton checkbuttonSquadListGiven;
		
		private global::Gtk.CheckButton checkbuttonWonBye;
		
		private global::Gtk.Entry entryCity;
		
		private global::Gtk.Entry entryT3ID;
		
		private global::Gtk.Label labelCity;
		
		private global::Gtk.Label labelInfoTableNr;
		
		private global::Gtk.Label labelT3ID;
		
		private global::Gtk.Label labelTableNr;
		
		private global::Gtk.SpinButton spinbuttonTableNr;
		
		private global::Gtk.Label labelTabAdvanced;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget TXM.PlayerDialog
			this.Name = "TXM.PlayerDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child TXM.PlayerDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.table1 = new global::Gtk.Table (((uint)(7)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.checkbuttonPresent = new global::Gtk.CheckButton ();
			this.checkbuttonPresent.CanFocus = true;
			this.checkbuttonPresent.Name = "checkbuttonPresent";
			this.checkbuttonPresent.Label = global::Mono.Unix.Catalog.GetString ("Present");
			this.checkbuttonPresent.DrawIndicator = true;
			this.checkbuttonPresent.UseUnderline = true;
			this.table1.Add (this.checkbuttonPresent);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkbuttonPresent]));
			w2.TopAttach = ((uint)(5));
			w2.BottomAttach = ((uint)(6));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.comboboxFaction = global::Gtk.ComboBox.NewText ();
			this.comboboxFaction.Name = "comboboxFaction";
			this.table1.Add (this.comboboxFaction);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.comboboxFaction]));
			w3.TopAttach = ((uint)(4));
			w3.BottomAttach = ((uint)(5));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryForeName = new global::Gtk.Entry ();
			this.entryForeName.CanFocus = true;
			this.entryForeName.Name = "entryForeName";
			this.entryForeName.IsEditable = true;
			this.entryForeName.InvisibleChar = '●';
			this.table1.Add (this.entryForeName);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.entryForeName]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryLastName = new global::Gtk.Entry ();
			this.entryLastName.CanFocus = true;
			this.entryLastName.Name = "entryLastName";
			this.entryLastName.IsEditable = true;
			this.entryLastName.InvisibleChar = '●';
			this.table1.Add (this.entryLastName);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.entryLastName]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryNickName = new global::Gtk.Entry ();
			this.entryNickName.CanFocus = true;
			this.entryNickName.Name = "entryNickName";
			this.entryNickName.IsEditable = true;
			this.entryNickName.InvisibleChar = '●';
			this.table1.Add (this.entryNickName);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.entryNickName]));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryTeam = new global::Gtk.Entry ();
			this.entryTeam.CanFocus = true;
			this.entryTeam.Name = "entryTeam";
			this.entryTeam.IsEditable = true;
			this.entryTeam.InvisibleChar = '●';
			this.table1.Add (this.entryTeam);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.entryTeam]));
			w7.TopAttach = ((uint)(3));
			w7.BottomAttach = ((uint)(4));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelFaction = new global::Gtk.Label ();
			this.labelFaction.Name = "labelFaction";
			this.labelFaction.LabelProp = global::Mono.Unix.Catalog.GetString ("Faction");
			this.table1.Add (this.labelFaction);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelFaction]));
			w8.TopAttach = ((uint)(4));
			w8.BottomAttach = ((uint)(5));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelForeName = new global::Gtk.Label ();
			this.labelForeName.Name = "labelForeName";
			this.labelForeName.LabelProp = global::Mono.Unix.Catalog.GetString ("Forename*");
			this.table1.Add (this.labelForeName);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelForeName]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelInfoName = new global::Gtk.Label ();
			this.labelInfoName.Name = "labelInfoName";
			this.labelInfoName.LabelProp = global::Mono.Unix.Catalog.GetString ("* Nickname or ForeName and\nLastname has to be given.");
			this.table1.Add (this.labelInfoName);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelInfoName]));
			w10.TopAttach = ((uint)(6));
			w10.BottomAttach = ((uint)(7));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelLastName = new global::Gtk.Label ();
			this.labelLastName.Name = "labelLastName";
			this.labelLastName.LabelProp = global::Mono.Unix.Catalog.GetString ("Lastname*");
			this.table1.Add (this.labelLastName);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelLastName]));
			w11.TopAttach = ((uint)(2));
			w11.BottomAttach = ((uint)(3));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelNickname = new global::Gtk.Label ();
			this.labelNickname.Name = "labelNickname";
			this.labelNickname.LabelProp = global::Mono.Unix.Catalog.GetString ("Nickname*");
			this.table1.Add (this.labelNickname);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelNickname]));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelTeam = new global::Gtk.Label ();
			this.labelTeam.Name = "labelTeam";
			this.labelTeam.LabelProp = global::Mono.Unix.Catalog.GetString ("Team");
			this.table1.Add (this.labelTeam);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelTeam]));
			w13.TopAttach = ((uint)(3));
			w13.BottomAttach = ((uint)(4));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			this.notebook1.Add (this.table1);
			// Notebook tab
			this.labelTabBasic = new global::Gtk.Label ();
			this.labelTabBasic.Name = "labelTabBasic";
			this.labelTabBasic.LabelProp = global::Mono.Unix.Catalog.GetString ("Basic");
			this.notebook1.SetTabLabel (this.table1, this.labelTabBasic);
			this.labelTabBasic.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.table3 = new global::Gtk.Table (((uint)(8)), ((uint)(2)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.checkbuttonDisqualified = new global::Gtk.CheckButton ();
			this.checkbuttonDisqualified.Sensitive = false;
			this.checkbuttonDisqualified.CanFocus = true;
			this.checkbuttonDisqualified.Name = "checkbuttonDisqualified";
			this.checkbuttonDisqualified.Label = global::Mono.Unix.Catalog.GetString ("Disqualified");
			this.checkbuttonDisqualified.DrawIndicator = true;
			this.checkbuttonDisqualified.UseUnderline = true;
			this.table3.Add (this.checkbuttonDisqualified);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table3 [this.checkbuttonDisqualified]));
			w15.TopAttach = ((uint)(6));
			w15.BottomAttach = ((uint)(7));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.checkbuttonPaid = new global::Gtk.CheckButton ();
			this.checkbuttonPaid.CanFocus = true;
			this.checkbuttonPaid.Name = "checkbuttonPaid";
			this.checkbuttonPaid.Label = global::Mono.Unix.Catalog.GetString ("Paid");
			this.checkbuttonPaid.DrawIndicator = true;
			this.checkbuttonPaid.UseUnderline = true;
			this.table3.Add (this.checkbuttonPaid);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table3 [this.checkbuttonPaid]));
			w16.TopAttach = ((uint)(3));
			w16.BottomAttach = ((uint)(4));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.checkbuttonSquadListGiven = new global::Gtk.CheckButton ();
			this.checkbuttonSquadListGiven.CanFocus = true;
			this.checkbuttonSquadListGiven.Name = "checkbuttonSquadListGiven";
			this.checkbuttonSquadListGiven.Label = global::Mono.Unix.Catalog.GetString ("Squadlist Given");
			this.checkbuttonSquadListGiven.DrawIndicator = true;
			this.checkbuttonSquadListGiven.UseUnderline = true;
			this.table3.Add (this.checkbuttonSquadListGiven);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table3 [this.checkbuttonSquadListGiven]));
			w17.TopAttach = ((uint)(5));
			w17.BottomAttach = ((uint)(6));
			w17.LeftAttach = ((uint)(1));
			w17.RightAttach = ((uint)(2));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.checkbuttonWonBye = new global::Gtk.CheckButton ();
			this.checkbuttonWonBye.CanFocus = true;
			this.checkbuttonWonBye.Name = "checkbuttonWonBye";
			this.checkbuttonWonBye.Label = global::Mono.Unix.Catalog.GetString ("Won Bye");
			this.checkbuttonWonBye.DrawIndicator = true;
			this.checkbuttonWonBye.UseUnderline = true;
			this.table3.Add (this.checkbuttonWonBye);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table3 [this.checkbuttonWonBye]));
			w18.TopAttach = ((uint)(4));
			w18.BottomAttach = ((uint)(5));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entryCity = new global::Gtk.Entry ();
			this.entryCity.CanFocus = true;
			this.entryCity.Name = "entryCity";
			this.entryCity.IsEditable = true;
			this.entryCity.InvisibleChar = '●';
			this.table3.Add (this.entryCity);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table3 [this.entryCity]));
			w19.TopAttach = ((uint)(1));
			w19.BottomAttach = ((uint)(2));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entryT3ID = new global::Gtk.Entry ();
			this.entryT3ID.CanFocus = true;
			this.entryT3ID.Name = "entryT3ID";
			this.entryT3ID.IsEditable = true;
			this.entryT3ID.InvisibleChar = '●';
			this.table3.Add (this.entryT3ID);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table3 [this.entryT3ID]));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.labelCity = new global::Gtk.Label ();
			this.labelCity.Name = "labelCity";
			this.labelCity.LabelProp = global::Mono.Unix.Catalog.GetString ("City");
			this.table3.Add (this.labelCity);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table3 [this.labelCity]));
			w21.TopAttach = ((uint)(1));
			w21.BottomAttach = ((uint)(2));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.labelInfoTableNr = new global::Gtk.Label ();
			this.labelInfoTableNr.Name = "labelInfoTableNr";
			this.labelInfoTableNr.LabelProp = global::Mono.Unix.Catalog.GetString ("* If the player needs a fixed\ntable (e. g. wheelchair users).");
			this.table3.Add (this.labelInfoTableNr);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table3 [this.labelInfoTableNr]));
			w22.TopAttach = ((uint)(7));
			w22.BottomAttach = ((uint)(8));
			w22.LeftAttach = ((uint)(1));
			w22.RightAttach = ((uint)(2));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.labelT3ID = new global::Gtk.Label ();
			this.labelT3ID.Name = "labelT3ID";
			this.labelT3ID.LabelProp = global::Mono.Unix.Catalog.GetString ("T3 ID");
			this.table3.Add (this.labelT3ID);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table3 [this.labelT3ID]));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.labelTableNr = new global::Gtk.Label ();
			this.labelTableNr.Name = "labelTableNr";
			this.labelTableNr.LabelProp = global::Mono.Unix.Catalog.GetString ("*Table No.");
			this.table3.Add (this.labelTableNr);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table3 [this.labelTableNr]));
			w24.TopAttach = ((uint)(2));
			w24.BottomAttach = ((uint)(3));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.spinbuttonTableNr = new global::Gtk.SpinButton (0, 1024, 1);
			this.spinbuttonTableNr.CanFocus = true;
			this.spinbuttonTableNr.Name = "spinbuttonTableNr";
			this.spinbuttonTableNr.Adjustment.PageIncrement = 1;
			this.spinbuttonTableNr.ClimbRate = 1;
			this.spinbuttonTableNr.Numeric = true;
			this.table3.Add (this.spinbuttonTableNr);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table3 [this.spinbuttonTableNr]));
			w25.TopAttach = ((uint)(2));
			w25.BottomAttach = ((uint)(3));
			w25.LeftAttach = ((uint)(1));
			w25.RightAttach = ((uint)(2));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			this.notebook1.Add (this.table3);
			global::Gtk.Notebook.NotebookChild w26 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.table3]));
			w26.Position = 1;
			// Notebook tab
			this.labelTabAdvanced = new global::Gtk.Label ();
			this.labelTabAdvanced.Name = "labelTabAdvanced";
			this.labelTabAdvanced.LabelProp = global::Mono.Unix.Catalog.GetString ("Advanced");
			this.notebook1.SetTabLabel (this.table3, this.labelTabAdvanced);
			this.labelTabAdvanced.ShowAll ();
			w1.Add (this.notebook1);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(w1 [this.notebook1]));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			// Internal child TXM.PlayerDialog.ActionArea
			global::Gtk.HButtonBox w28 = this.ActionArea;
			w28.Name = "dialog1_ActionArea";
			w28.Spacing = 10;
			w28.BorderWidth = ((uint)(5));
			w28.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w29 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w28 [this.buttonCancel]));
			w29.Expand = false;
			w29.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w30 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w28 [this.buttonOk]));
			w30.Position = 1;
			w30.Expand = false;
			w30.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 296;
			this.DefaultHeight = 322;
			this.Show ();
			this.buttonCancel.Clicked += new global::System.EventHandler (this.Cancel_Click);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OK_Click);
		}
	}
}
